[phases.setup]
nixPkgs = ["python312", "pip", "nodejs_18", "npm"]

[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "npm install",
    "npx tailwindcss -i static/src/input.css -o static/css/output.css --minify",
    "pip list"

]

[phases.start]
cmd = "python manage.py migrate && gunicorn jokehub.wsgi --bind 0.0.0.0:$PORT"