# Generated by Django 5.1.5 on 2025-02-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image/profile.png', null=True, upload_to='profile_image/'),
        ),
    ]
