# Generated by Django 5.1.5 on 2025-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_image\\profile.png', upload_to='profile_image/'),
        ),
    ]
