# Generated by Django 4.2.20 on 2025-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/dg0m3qgxt/image/upload/v1744208107/whkig5d0oafqfowlm2tw.png', upload_to='profile_image/'),
        ),
    ]
