# Generated by Django 4.2.20 on 2025-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_image',
            field=models.URLField(default='https://res.cloudinary.com/dg0m3qgxt/image/upload/v1744208107/whkig5d0oafqfowlm2tw.png', max_length=250),
        ),
    ]
