# Generated by Django 5.1.5 on 2025-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=310),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='jokes', max_length=7),
        ),
    ]
