# Generated by Django 5.1.5 on 2025-03-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0004_alter_post_content_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
